import { createRequire } from 'module';

// eslint-disable-next-line no-unused-vars
const require = createRequire(import.meta.url);

/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      fontFamily: {
        sans: ["Arial", "sans-serif"],
        "body-md": ["Arial", "sans-serif"],
        "label-sm": ["Arial", "sans-serif"],
        "display-md": ["Arial", "sans-serif"],
        "display-lg": ["Arial", "sans-serif"],
        "body-sm": ["Arial", "sans-serif"],
        "body-lg": ["Arial", "sans-serif"],
        "headline-sm": ["Arial", "sans-serif"],
        "label-md": ["Arial", "sans-serif"],
      },
      colors: {
        "on-primary-fixed-variant": "#0a3fa4",
        "surface-tint": "#3058bd",
        "inverse-primary": "#b4c5ff",
        "on-tertiary-fixed-variant": "#005138",
        "primary-fixed-dim": "#b4c5ff",
        primary: "#002b7a",
        "on-secondary": "#ffffff",
        "tertiary-container": "#005339",
        "surface-bright": "#f7f9fb",
        "on-background": "#191c1e",
        "on-primary-fixed": "#00174b",
        "surface-container-high": "#e6e8ea",
        "tertiary-fixed": "#78fac3",
        "tertiary-fixed-dim": "#59dda9",
        "surface-container-highest": "#e0e3e5",
        "on-secondary-fixed-variant": "#344862",
        "on-tertiary-container": "#47cd9a",
        "primary-fixed": "#dbe1ff",
        "secondary-fixed": "#d2e4ff",
        "secondary-fixed-dim": "#b3c8e7",
        "surface-container-low": "#f2f4f6",
        "error-container": "#ffdad6",
        "surface-variant": "#e0e3e5",
        "on-secondary-container": "#4e627d",
        secondary: "#4c607a",
        "surface-dim": "#d8dadc",
        "on-tertiary": "#ffffff",
        "secondary-container": "#cadefe",
        "outline-variant": "#c4c6d5",
        "surface-container": "#eceef0",
        "surface-container-lowest": "#ffffff",
        tertiary: "#003a27",
        "on-primary": "#ffffff",
        "on-surface": "#191c1e",
        error: "#ba1a1a",
        surface: "#f7f9fb",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "inverse-on-surface": "#eff1f3",
        background: "#f7f9fb",
        "on-secondary-fixed": "#051c34",
        "on-primary-container": "#9db4ff",
        "inverse-surface": "#2d3133",
        outline: "#747684",
        "on-tertiary-fixed": "#002114",
        "on-surface-variant": "#434653",
        "primary-container": "#0d40a5",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        gutter: "16px",
        "section-gap": "32px",
        "compact-padding": "8px",
        "container-margin": "24px",
        unit: "4px",
        "card-padding": "20px",
      },
      fontSize: {
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-sm": ["11px", { lineHeight: "14px", fontWeight: "500" }],
        "display-md": [
          "24px",
          { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "display-lg": [
          "30px",
          { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-md": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" },
        ],
      },
      keyframes: {
        shake: {
          "0%, 100%": { transform: "translateX(0) rotate(0deg)" },
          "10%, 30%, 50%, 70%, 90%": { transform: "translateX(-3px) rotate(-8deg)" },
          "20%, 40%, 60%, 80%": { transform: "translateX(3px) rotate(8deg)" },
        },
        "bell-ring": {
          "0%, 100%": { transform: "rotate(0deg)" },
          "10%, 30%": { transform: "rotate(-15deg)" },
          "20%, 40%": { transform: "rotate(15deg)" },
          "50%": { transform: "rotate(-10deg)" },
          "60%, 80%": { transform: "rotate(10deg)" },
          "70%": { transform: "rotate(-5deg)" },
          "90%": { transform: "rotate(5deg)" },
        },
      },
      animation: {
        shake: "shake 0.6s ease-in-out",
        "bell-ring": "bell-ring 0.8s ease-in-out",
      },
    },
  },
  plugins: [],
};
